ALTER TABLE [dbo].[OpenID]
    ADD CONSTRAINT [I_OauthUserID] PRIMARY KEY CLUSTERED ([OpenIdClaimedIdentifier] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

