ALTER TABLE [dbo].[Macro]
    ADD CONSTRAINT [PK_Macro] PRIMARY KEY CLUSTERED ([MacroID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

