ALTER TABLE [dbo].[MacroTags]
    ADD CONSTRAINT [PK_MacroTags] PRIMARY KEY CLUSTERED ([MacroID] ASC, [TagID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

