ALTER TABLE [dbo].[RankMacro]
    ADD CONSTRAINT [PK_RankMacro] PRIMARY KEY CLUSTERED ([MacroID] ASC, [UserID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

