ALTER TABLE [dbo].[ServersPlayedByUserID]
    ADD CONSTRAINT [PK_ServersPlayedByUserID] PRIMARY KEY CLUSTERED ([ServersPlayedByUserID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

