ALTER TABLE [dbo].[Tags]
    ADD CONSTRAINT [PK_Tags] PRIMARY KEY CLUSTERED ([TagID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

